import NextHead from 'next/head';
import NextLink from 'next/link';
import { ReactElement } from 'react';

import { MainLayout } from '../components/Layout';

const Home = () => {
  return (
    <>
      <NextHead>
        <title>Next.js Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </NextHead>

      <h1>Next.js Boilerplate</h1>

      <NextLink href="/content">to Content Page</NextLink>
    </>
  );
};

Home.getLayout = (page: ReactElement) => <MainLayout>{page}</MainLayout>;

export default Home;
