import { useSession } from "next-auth/react";
import NextHead from 'next/head';
import NextLink from 'next/link';
import { ReactElement } from 'react';

import { MainLayout } from '../components/Layout';
import { useBooksQuery } from "../hooks/useBooksQuery";

const Home = () => {
  const { data: session } = useSession();
  const { data } = useBooksQuery({
    variables: { session }
  });

  return (
    <>
      <NextHead>
        <title>Next.js Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </NextHead>

      <h1>Next.js Boilerplate</h1>

      {
        data && data?.books.map(({ id, title, author }) => {
          return <div key={id}>{title}, {author}</div>
        })
      }

      <div>
        <NextLink href="/content">to Content Page</NextLink>
      </div>

      <div>
        <NextLink href="/dashboard">to Dashboard Page</NextLink>
      </div>
    </>
  );
};

Home.getLayout = (page: ReactElement) => <MainLayout>{page}</MainLayout>;

export default Home;
